name: Build and Push the Docker image

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Inspect
        run:  |
          ls -a
      -
        name: Build
        uses: docker/build-push-action@v2
        id: test
        with:
          tags: action/docker:test
          context: .
      -
        name: Inspect
        run:  |
          ls -a
          docker --version
          docker images