name: Build and Push the Docker image

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Inspect
        run:  |
          ls -a
      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          tags: action/docker:demo
          context: .
      -
        name: Inspect
        run:  |
          ls -a
          docker --version
          docker images