name: Build and Push the Docker image

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Inspect
        run:  |
          ls -a